### ISSUE TITLE
Training crashes with error (rare)

### ISSUE THREAD

**Issue by nkemnitz** [ZettaAI/zetta_utils#385]
```python
2023-05-02 14:46:21.174 ERROR    mazepa /home/nkemnitz/zetta/zetta_utils/zetta_utils/mazepa/execution_state.py: 133
                                 Task traceback: Traceback (most recent call last):
                                   File "/opt/zetta_utils/zetta_utils/mazepa/tasks.py", line 188, in _call_without_upkeep
                                     return_value = self.fn(*self.args, **self.kwargs)
                                   File "/opt/zetta_utils/zetta_utils/builder/build.py", line 206, in __call__
                                     result = fn(
                                   File "/usr/local/lib/python3.9/dist-packages/typeguard/_decorators.py", line 136, in wrapper
                                     retval = func(*args, **kwargs)
                                   File "/opt/zetta_utils/zetta_utils/training/lightning/train.py", line 58, in lightning_train
                                     trainer.fit(
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
                                     self._call_and_handle_interrupt(
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
                                     return trainer_fn(*args, **kwargs)
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
                                     results = self._run(model, ckpt_path=self.ckpt_path)
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
                                     results = self._run_stage()
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
                                     return self._run_train()
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1283, in _run_train
                                     self.fit_loop.run()
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/loop.py", line 200, in run
                                     self.advance(*args, **kwargs)
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/fit_loop.py", line 271, in advance
                                     self._outputs = self.epoch_loop.run(self._data_fetcher)
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/loop.py", line 200, in run
                                     self.advance(*args, **kwargs)
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 219, in advance
                                     self.trainer._call_callback_hooks("on_train_batch_end", batch_end_outputs, batch, batch_idx)
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1597, in _call_callback_hooks
                                     fn(self, self.lightning_module, *args, **kwargs)
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 303, in on_train_batch_end
                                     self._save_topk_checkpoint(trainer, monitor_candidates)
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 384, in _save_topk_checkpoint
                                     self._save_none_monitor_checkpoint(trainer, monitor_candidates)
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 674, in _save_none_monitor_checkpoint
                                     trainer.strategy.remove_checkpoint(previous)
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/strategies/strategy.py", line 455, in remove_checkpoint
                                     self.checkpoint_io.remove_checkpoint(filepath)
                                   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/plugins/io/torch_plugin.py", line 95, in remove_checkpoint
                                     fs.rm(path, recursive=True)
                                   File "/usr/local/lib/python3.9/dist-packages/fsspec/asyn.py", line 115, in wrapper
                                     return sync(self.loop, func, *args, **kwargs)
                                   File "/usr/local/lib/python3.9/dist-packages/fsspec/asyn.py", line 100, in sync
                                     raise return_result
                                   File "/usr/local/lib/python3.9/dist-packages/fsspec/asyn.py", line 55, in _runner
                                     result[0] = await coro
                                   File "/usr/local/lib/python3.9/dist-packages/gcsfs/core.py", line 1085, in _rm
                                     raise exs[0]
                                   File "/usr/local/lib/python3.9/dist-packages/gcsfs/core.py", line 1050, in _rm_files
                                     raise OSError(errors)
                                 OSError: ['We encountered an internal error. Please try again.']
```

**Comment by supersergiy** [comment]
This should be fixable by adding a transient error condition
