### ISSUE TITLE
Runtime error: can't start new thread

### ISSUE THREAD

**Issue by nkemnitz** [ZettaAI/zetta_utils#531]
Training ran for 301 minutes on a single node with single GPU and 20 dataloader workers.

```python
RuntimeError: Caught RuntimeError in DataLoader worker process 13.
Original Traceback (most recent call last):
  File "/home/nkemnitz/zetta/zetta_utils/venv/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/nkemnitz/zetta/zetta_utils/venv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nkemnitz/zetta/zetta_utils/venv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nkemnitz/zetta/zetta_utils/zetta_utils/training/datasets/joint_dataset.py", line 67, in __getitem__
    sample[key] = dset[idx]
  File "/home/nkemnitz/zetta/zetta_utils/zetta_utils/training/datasets/joint_dataset.py", line 74, in __getitem__
    sample = dset[idx - sum_num_samples]
  File "/home/nkemnitz/zetta/zetta_utils/zetta_utils/training/datasets/layer_dataset.py", line 48, in __getitem__
    sample_raw = self.layer.read_with_procs(layer_idx)
  File "/home/nkemnitz/zetta/zetta_utils/zetta_utils/layer/layer_base.py", line 44, in read_with_procs
    data_backend = self.backend.read(idx=idx_proced)
  File "/home/nkemnitz/zetta/zetta_utils/zetta_utils/layer/layer_set/backend.py", line 19, in read
    return {k: v.read_with_procs(idx) for k, v in self.layers.items()}
  File "/home/nkemnitz/zetta/zetta_utils/zetta_utils/layer/layer_set/backend.py", line 19, in <dictcomp>
    return {k: v.read_with_procs(idx) for k, v in self.layers.items()}
  File "/home/nkemnitz/zetta/zetta_utils/zetta_utils/layer/layer_base.py", line 44, in read_with_procs
    data_backend = self.backend.read(idx=idx_proced)
  File "/home/nkemnitz/zetta/zetta_utils/zetta_utils/layer/volumetric/cloudvol/backend.py", line 203, in read
    data_raw = cvol[idx.to_slices()]
  File "/home/nkemnitz/zetta/zetta_utils/venv/lib/python3.9/site-packages/cloudvolume/frontends/precomputed.py", line 551, in __getitem__
    img = self.download(requested_bbox, self.mip)
  File "/home/nkemnitz/zetta/zetta_utils/venv/lib/python3.9/site-packages/cloudvolume/frontends/precomputed.py", line 731, in download
    tup = self.image.download(
  File "/home/nkemnitz/zetta/zetta_utils/venv/lib/python3.9/site-packages/cloudvolume/datasource/precomputed/image/__init__.py", line 200, in download
    return rx.download(
  File "/home/nkemnitz/zetta/zetta_utils/venv/lib/python3.9/site-packages/cloudvolume/datasource/precomputed/image/rx.py", line 295, in download
    download_chunks_threaded(
  File "/home/nkemnitz/zetta/zetta_utils/venv/lib/python3.9/site-packages/cloudvolume/datasource/precomputed/image/rx.py", line 599, in download_chunks_threaded
    schedule_jobs(
  File "/home/nkemnitz/zetta/zetta_utils/venv/lib/python3.9/site-packages/cloudvolume/scheduler.py", line 150, in schedule_jobs
    return schedule_threaded_jobs(fns, concurrency, progress, total)
  File "/home/nkemnitz/zetta/zetta_utils/venv/lib/python3.9/site-packages/cloudvolume/scheduler.py", line 37, in schedule_threaded_jobs
    with ThreadedQueue(n_threads=concurrency) as tq:
  File "/home/nkemnitz/zetta/zetta_utils/venv/lib/python3.9/site-packages/cloudvolume/threaded_queue.py", line 29, in __init__
    self.start_threads(n_threads)
  File "/home/nkemnitz/zetta/zetta_utils/venv/lib/python3.9/site-packages/cloudvolume/threaded_queue.py", line 85, in start_threads
    worker.start()
  File "/home/nkemnitz/zetta/zetta_utils/venv/lib/python3.9/threading.py", line 899, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

`ulimit -u` on this system returns 256585. I don't know how many threads were actually in use at the time. Will keep an eye on that number today, as well as on that 300 minute mark.

**Comment by nkemnitz** [comment]
Re-ran with 16 dataloader workers and tracked the total number of threads. Thread count never went over 700 and training continued for 12 hours with no interruption. Going to close this for now.
