### ISSUE TITLE
Training on GCP instance crashes after a number of iterations

### ISSUE THREAD

**Issue by dodamih** [ZettaAI/zetta_utils#94]
A dataloader process seems to consistently die when training using lightning after some number of iterations that depends on the training. An example error log:

`Epoch 31/99 ━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━ 2515/4070 0:16:12 • 0:06:32 3.98it/s loss: 0.0626 v_num: 1.25 
Traceback (most recent call last):
  File "/home/dodam/zetta_utils/zetta_utils/builder/parser.py", line 99, in _build
    result = registered_fn(**fn_kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/home/dodam/zetta_utils/zetta_utils/training/lightning/train.py", line 22, in lighning_train
    trainer.fit(
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1283, in _run_train
    self.fit_loop.run()
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 271, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 203, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 87, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 201, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 248, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 358, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1550, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1705, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 216, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 153, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/torch/optim/adam.py", line 118, in step
    loss = closure()
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 138, in _wrap_closure
    closure_result = closure()
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 146, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 132, in closure
    step_output = self._step_fn()
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 407, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1704, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 358, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/home/dodam/zetta_utils/zetta_utils/training/lightning/regimes/misalignment_detector.py", line 103, in training_step
    loss = self.compute_loss(image, field0, field1, "train", log_row)
  File "/home/dodam/zetta_utils/zetta_utils/training/lightning/regimes/misalignment_detector.py", line 123, in compute_loss
    field0 = self.augment_field(field0)
  File "/home/dodam/zetta_utils/zetta_utils/training/lightning/regimes/misalignment_detector.py", line 63, in augment_field
    return scale * random_horizontal_flip(random_vertical_flip(torchvision.transforms.functional.rotate(field, angle)))
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/torchvision/transforms/functional.py", line 1081, in rotate
    return F_t.rotate(img, matrix=matrix, interpolation=interpolation.value, expand=expand, fill=fill)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py", line 691, in rotate
    grid = _gen_affine_grid(theta, w=w, h=h, ow=ow, oh=oh)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py", line 628, in _gen_affine_grid
    output_grid = base_grid.view(1, oh * ow, 3).bmm(rescaled_theta)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1459186) is killed by signal: Killed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dodam/miniconda3/envs/zu/bin/zetta", line 33, in <module>
    sys.exit(load_entry_point('zetta-utils', 'console_scripts', 'zetta')())
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/dodam/zetta_utils/zetta_utils/cli/main.py", line 29, in run
    result = zu.builder.build(spec)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/home/dodam/zetta_utils/zetta_utils/builder/parser.py", line 60, in build
    result = _build(spec)
  File "/home/dodam/miniconda3/envs/zu/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/home/dodam/zetta_utils/zetta_utils/builder/parser.py", line 101, in _build
    raise RuntimeError(
RuntimeError: Exception while building "@type": lightning_train (mapped to zetta_utils.training.lightning.train.lighning_train), "@mode": regular
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb:
wandb:
wandb: Run history:
wandb:               epoch ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▆▇▇▇▇▇███
wandb:    loss/train_epoch █▃▄▂▅▁▂▂▂▁▁▁▂▂▁▁▃▂▁▂▁▁▂▁▂▁▁▂▁▂▂▁▂▁▁▁▁▂▁▁
wandb:     loss/train_step █▃▆▁▁▂▁▂▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: loss/validate_epoch █▄█▁▁▂▂▂▂▁▂▁▂▁▁▂▁▁▁▁▁▁▁▁▁▁▁▂▁▁▁▁▂▁▁▁▁▁▁▁
wandb:  loss/validate_step ▆▃█▁▁▁▂▂▂▁▂▁▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▁▁▁▁▁▁▁
wandb: trainer/global_step ▁▁▁▂▂▂▂▁▁▃▃▃▁▁▁▁▄▁▄▁▁▁▅▆▆▁▁▆▇▇▇▇▁▁███▁▁▁
wandb:
wandb: Run summary:
wandb:               epoch 31
wandb:    loss/train_epoch 0.02623
wandb:     loss/train_step 0.07257
wandb: loss/validate_epoch 0.02623
wandb:  loss/validate_step 0.03642
wandb: trainer/global_step 126199
wandb:
wandb: Synced unet_zfish_emb_m5_max5.0_flip_aug0.25-1.25: https://wandb.ai/dodam/misalignment_detector/runs/unet_zfish_emb_m5_max5.0_flip_aug0.25-1.25
wandb: Synced 5 W&B file(s), 11914 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20221105_074817-unet_zfish_emb_m5_max5.0_flip_aug0.25-1.25/logs
(zu) dodam@dodam-zettautils:~/zetta_utils/specs/examples/training$ fg`

**Comment by supersergiy** [comment]
This seems to be caused by memory leak caused by `pyplot`-ing images for wandb logging.
To use pyplot without memory leaks is not trivial, but it should be now implemented in https://github.com/ZettaAI/zetta_utils/blob/main/zetta_utils/viz/rendering.py
To avoid the memory leak, it's recommended to use the rendering functions outlined there as opposed to rolling out custom stuff.
